name: iancampbell
favicon: null
layout_spectrum: 0.27375
typography_spectrum: 0.40946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#334046'
    - '#1d2528'
    - '#6e8094'
    - '#91a3b1'
    - '#6e674a'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
