name: INCDP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40946
title: 'Ian Nicholas Campbell - Cinematographer '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#334046'
    - '#1d2528'
    - '#6e8094'
    - '#91a3b1'
    - '#6e674a'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
