name: iancampbell
favicon: null
layout_spectrum: 0.07531476230360568
typography_spectrum: 0.7110157187562436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.599424741929397
  lightness: 0.5761413085274398
  saturation: 0.7184607873205096
  rhythmicContrast: 0.9938044948503375
purpose: []
